### ISSUE TITLE
Question: Google or BlueJeans?

### ISSUE THREAD

**Issue by gvwilson** [katieannemills/SWC-bug-bbq#2]
Should we use Google Hangouts or BlueJeans for video conferencing?

**Comment by katieannemills** [comment]
Since teleconferencing is always the biggest gong show to centrally organize, we were thinking of keeping things pretty DIY per lesson in that respect; we're going to set up an etherpad for each one and encourage the use of that as a central point of communication and coordination, and if the maintainers want to hang out in a hang out to voice chat with folks, they're welcome to set one up and link it from their etherpad. So, I guess that means the defacto answer to your question is Google Hangouts. @ttimbers, thoughts?

**Comment by ttimbers** [comment]
@BillMills - sounds good to me.
